<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Forms + form_fields — embeddable lead-capture forms.
 *
 * A form is a slugged, public endpoint. Two parties hit it:
 *
 *   - Browsers via the embed script (POST /forms/{slug}/submit) —
 *     plain form data, honeypot + per-IP rate limit, no signature.
 *
 *   - Other systems via the webhook (POST /webhooks/{slug}) —
 *     JSON body, HMAC-SHA256 signed with webhook_secret in the
 *     X-Webhook-Signature header. VerifyFormWebhookSignature
 *     middleware loads the form by slug, reads the secret,
 *     hash_equals'es it before the controller even runs.
 *
 * Each submission lives in form_submissions (separate migration)
 * and fires the WorkflowEngine — which is what actually turns
 * raw submissions into leads, tasks, and notes.
 *
 * Fields are stored relationally (not in a JSON blob on forms)
 * so the form builder UI can drag-reorder them and the public
 * submit endpoint can validate required/email rules without
 * reaching back into the parent record.
 */
return new class() extends Migration
{
    public function up(): void
    {
        Schema::create('forms', function (Blueprint $table) {
            $table->id();

            $table->string('name');
            $table->text('description')->nullable();

            // slug is what appears in every public URL:
            //   /forms/{slug}/submit
            //   /forms/{slug}/embed.js
            //   /webhooks/{slug}
            // The form builder validates regex:/^[a-z0-9-]+$/.
            $table->string('slug', 100)->unique();

            $table->enum('status', ['active', 'inactive', 'draft'])
                ->default('draft');

            // Styling / messaging.
            $table->string('submit_button_text', 100)->default('Submit');
            $table->text('success_message')->nullable();
            // If set, takes precedence over success_message — the
            // browser is redirected here after a successful submit.
            $table->string('redirect_url', 500)->nullable();

            // GDPR. When enabled the embed script renders a
            // required checkbox with this consent copy.
            $table->boolean('gdpr_consent_enabled')->default(false);
            $table->text('gdpr_consent_text')->nullable();

            // HMAC key for the inbound webhook route.
            // 32 hex chars = 16 bytes of entropy; generated by
            // FormBuilderController::store() via Str::random(32).
            $table->string('webhook_secret', 64);

            // Counter increment'd on every successful submission.
            // Denormalised so the index page doesn't need to
            // count(form_submissions) per row.
            $table->integer('submission_count')->default(0);

            $table->foreignId('created_by')
                ->constrained('users')->restrictOnDelete();
            $table->timestamps();

            $table->index(['slug', 'status']);
        });

        Schema::create('form_fields', function (Blueprint $table) {
            $table->id();
            $table->foreignId('form_id')
                ->constrained('forms')->cascadeOnDelete();

            $table->string('label');

            // The POST field name; snake_case enforced in the
            // builder. The WorkflowEngine references these keys
            // verbatim when mapping submission -> lead columns
            // (e.g. {"first_name_field": "first_name"}).
            $table->string('field_key', 100);

            $table->enum('type', [
                'text', 'email', 'phone', 'textarea',
                'select', 'radio', 'checkbox', 'number',
                'date', 'hidden',
            ])->default('text');

            $table->string('placeholder')->nullable();
            $table->string('default_value')->nullable();

            // For select / radio / checkbox group: ["Yes","No"].
            $table->json('options')->nullable();

            $table->boolean('is_required')->default(false);

            // Per-field extras beyond required/email — e.g.
            // {"min_length": 3, "max_length": 200}.
            $table->json('validation_rules')->nullable();

            $table->integer('sort_order')->default(0);
            $table->timestamps();

            $table->index(['form_id', 'sort_order']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('form_fields');
        Schema::dropIfExists('forms');
    }
};
