<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Two thin additions to the contracts row so the Contracts tab can
 * carry the operator's plain-English summary (description) and
 * surface the upload's friendly filename next to its uuid storage
 * path. We keep `notes` separate — that's the internal-only field;
 * `description` is what the customer-facing surface would render.
 */
return new class() extends Migration
{
    public function up(): void
    {
        Schema::table('contracts', function (Blueprint $table): void {
            $table->text('description')->nullable()->after('title');
            // Original filename matters only for the download header,
            // never for storage paths — those are uuid-generated by
            // FileUploadService to avoid trusting client filenames.
            $table->string('file_original_name', 255)->nullable()->after('pdf_path');
        });
    }

    public function down(): void
    {
        Schema::table('contracts', function (Blueprint $table): void {
            $table->dropColumn(['description', 'file_original_name']);
        });
    }
};
