<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Proposals — quotes sent to prospects, accepted online via a
 * signed token link, optionally converted into a contract.
 *
 * - reference (PROP-2026-0001) is human-facing and unique;
 *   generated by Proposal::generateNextReference() inside the
 *   creating transaction.
 * - acceptance_token is opaque (sha256 of internal + key + random).
 *   We invalidate it on accept so the link is single-use.
 * - accepted_at / accepted_ip / accepted_user_agent capture an
 *   audit trail strong enough to stand up as a binding click-
 *   accept; courts have ruled these are sufficient where the
 *   accept-button + tick-box + name field flow is clear.
 * - pdf_path = the "unsigned" PDF generated at send-time.
 *   accepted_pdf_path = a second PDF stamped with the acceptance
 *   block — what we ship into Contracts on conversion.
 *
 * customer_id is RESTRICT because losing the customer would
 * orphan a legally-binding accepted document.
 */
return new class() extends Migration
{
    public function up(): void
    {
        Schema::create('proposals', function (Blueprint $table) {
            $table->id();
            $table->foreignId('customer_id')
                ->constrained('customers')->restrictOnDelete();
            $table->foreignId('billing_entity_id')->nullable()
                ->constrained('billing_entities')->nullOnDelete();
            $table->foreignId('project_id')->nullable()
                ->constrained('projects')->nullOnDelete();
            $table->foreignId('contract_id')->nullable()
                ->constrained('contracts')->nullOnDelete();
            $table->string('reference', 20)->unique();
            $table->string('title');
            $table->text('description')->nullable();
            $table->text('terms')->nullable();
            $table->enum('status', ['draft', 'sent', 'accepted', 'rejected', 'expired'])
                ->default('draft');
            $table->decimal('subtotal', 10, 2)->default(0);
            $table->decimal('discount_amount', 10, 2)->default(0);
            $table->decimal('vat_rate', 5, 2)->default(20.00);
            $table->decimal('vat_amount', 10, 2)->default(0);
            $table->decimal('total', 10, 2)->default(0);
            $table->date('valid_until')->nullable();
            $table->timestamp('sent_at')->nullable();
            $table->string('acceptance_token', 64)->nullable()->unique();
            $table->timestamp('acceptance_token_expires_at')->nullable();
            $table->timestamp('accepted_at')->nullable();
            $table->string('accepted_by_name')->nullable();
            $table->string('accepted_ip', 45)->nullable();
            $table->text('accepted_user_agent')->nullable();
            $table->timestamp('rejected_at')->nullable();
            $table->text('rejection_reason')->nullable();
            $table->string('pdf_path', 500)->nullable();
            $table->string('accepted_pdf_path', 500)->nullable();
            $table->text('notes')->nullable();
            $table->foreignId('created_by')
                ->constrained('users')->restrictOnDelete();
            $table->timestamps();

            $table->index(['customer_id', 'status']);
            // acceptance_token index is created automatically by unique().
            // reference index is created automatically by unique().
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('proposals');
    }
};
