<?php

/*
|--------------------------------------------------------------------------
| Referral attribution
|--------------------------------------------------------------------------
| Single source for the /r/{code} redirect behaviour and the attribution
| window. Destination URLs are keyed by App\Enums\ProductKey value; an
| unknown or missing `p` param falls back to `default`.
*/

return [
    // First-party signed cookie dropped on the hub domain by the redirect.
    'cookie_name' => 'wd_ref',

    // Last-touch attribution window, in days.
    'window_days' => 60,

    // Where /r/{code}?p=<key> sends the visitor. Override per-environment
    // via env if these ever diverge from the marketing sites.
    'default' => env('REFERRAL_DEFAULT_DESTINATION', env('APP_URL', 'https://whitedash.com')),

    'destinations' => [
        'maavelus' => env('REFERRAL_DEST_MAAVELUS', 'https://maavelus.com'),
        'orderpad' => env('REFERRAL_DEST_ORDERPAD', 'https://myorderpad.com'),
        'whitedash' => env('REFERRAL_DEST_WHITEDASH', 'https://whitedash.com'),
        'estia' => env('REFERRAL_DEST_ESTIA', 'https://whitedash.com'),
        'comnicube' => env('REFERRAL_DEST_COMNICUBE', 'https://whitedash.com'),
        'other' => env('REFERRAL_DEST_OTHER', 'https://whitedash.com'),
    ],

    // Max length accepted for the free-text campaign (`c`) param at ingest.
    'campaign_max' => 100,

    // Deal registration: fixed protection window (days) from APPROVAL.
    'protection_days' => 90,

    // The self-serve product (by products.slug). The "Register a deal"
    // form surfaces this product's share-link alongside it so a referrer
    // can either register manually OR just share their link.
    'self_serve_slug' => env('REFERRAL_SELF_SERVE_SLUG', 'orderpad'),

    // Commission engine — products (by products.slug) whose referral
    // commissions are generated by their OWN flow (Maavelus monthly
    // statements) and must therefore be SKIPPED by the invoice-paid engine,
    // so revenue is never double-counted. Mirrors self_serve_slug's
    // config-driven shape.
    'commission_excluded_slugs' => ['maavelus', 'maavelus-hospitality'],
];
